### ISSUE TITLE
"riichi won" and "riichi in yaku stats" are not equal

### ISSUE THREAD

**Issue by alexeydergunov** [MahjongPantheon/pantheon#310]
wins with riichi: 71
riichi bets won: 71
riichi in yaku stats: 70

![изображение](https://user-images.githubusercontent.com/4611241/229793928-9dbe6007-0f85-4ab9-8e07-97df2e98ab28.png)

https://rating.riichimahjong.org/eid146/user/187

**71 / 71 / 70**

**Comment by alexeydergunov** [comment]
https://rating.riichimahjong.org/eid146/user/743 
also not equal

- выигрышей с риичи: 57
- [ставок риичи] из них выигранных: 55
- на диаграмме с яку: 57

**Comment by alexeydergunov** [comment]
1st and 3rd numbers may be not equal in case of double riichi.

If we calculate the sum of "riichi" and "double riichi" on the histogram, it is equal to "wins with riichi". So no bug here.

**Comment by alexeydergunov** [comment]
2nd number is number of riichi sticks won. Player can lose the sticks in case of double ron. I will investigate it more carefully, but on the first glance no bug here too.

**Comment by ctizen** [comment]
OK, let's reopen this if anything emerges
