### ISSUE TITLE
Wrong game timestamps

### ISSUE THREAD

**Issue by alexeydergunov** [MahjongPantheon/pantheon#311]
> например вот эта игра https://rating.riichimahjong.org/eid146/game/beec8b068bbda3732d4daf3f9088bdd3c8b9b333 имеет правильный таймстамп

> а эта https://rating.riichimahjong.org/eid146/game/660436f0b486a07dd04bfb854d85552747ef6902 на самом деле закончилась на 2 часа раньше, в 21:22

> если зайти в профиль любого игрока и кликать на точки на графике рейтинга, то там игры в правильном порядке, и как раз сбитое время можно будет обнаружить

**Comment by ctizen** [comment]
> for example this game https://rating.riichimahjong.org/eid146/game/beec8b068bbda3732d4daf3f9088bdd3c8b9b333 has the correct timestamp

> and this https://rating.riichimahjong.org/eid146/game/660436f0b486a07dd04bfb854d85552747ef6902 actually ended 2 hours early at 21:22

> if you go to the profile of any player and click on the dots on the rating graph, then there the games are in the correct order, and just the downed time can be found

**Comment by ctizen** [comment]
Probably fixed in https://github.com/MahjongPantheon/pantheon/commit/c79b022d2cfd766847267b14ba9ad383776e1a49 - check again

**Comment by alexeydergunov** [comment]
I think it is fixed now
