### ISSUE TITLE
"End game" button to force session finish

### ISSUE THREAD

**Issue by ctizen** [MahjongPantheon/pantheon#314]
Use case:
- Players use some external timer during club games, and after the time is expired they would like to end the game without adding bogus noten hands.

Suggestion:
- Add a "Force finish" button (or checkbox) either in admin panel or in mobile assistant. Having the checkbox checked will finish the game right after last hand is recorded.

**Comment by Jesterboxboy** [comment]
Adding it in admin panel would be better, as it would also allow the event administrator to finish old games, that players left unfinished.
In Frey, one of the Players would need to log in and finish it.
