### ISSUE TITLE
[Forseti improvement] Add view "Registered Tournaments"

### ISSUE THREAD

**Issue by Jesterboxboy** [MahjongPantheon/pantheon#334]
Adding a view for a player to see for which events they are enrolled in would be helpful.
Maybe adding "Enrolled/Registered Events" or something like that in Forset, with the option to click an enrolled event and be redirected to rating table in rheda.

**Comment by ctizen** [comment]
Now we have following:
- If a user has administrator privileges in event, this event is displayed in "Owned events" list in Forseti.
- If a user is enrolled to any event, the event is displayed in Tyr in event selection list.

Why would a user want to view the list of events they're enrolled in? :thinking:

**Comment by Jesterboxboy** [comment]
You are right, i completely forgot that the events you are registered for are displayed in Tyr. Someone brought that up, and i didn't think it all through it.
