### ISSUE TITLE
Более независимая i18n

### ISSUE THREAD

**Issue by exchange12rocks** [MahjongPantheon/pantheon#34]
Сейчас, английский перевод несёт на себе ещё и функцию placeholder'ов, что приводит к тому, что при изменении английского текста, менять одно и то же нужно в двух местах. Может быть стоит сделать placeholder'ы языконезависимыми?

**Comment by Nihisil** [comment]
Я тоже про это думал, чем больше будет языков, тем сложнее будет
поддерживать текущую реализацию.

**Comment by ctizen** [comment]
Тут вопрос - а как ты это себе представляешь? Плейсхолдеры к сожалению появились в инстраструктуре gettext не просто так: в разных языках может быть совершенно разная структура перечислений и грамматических конструкций. Например, в английском мы говорим "%d item[s] left". В русском мы не говорим "%d элемент[а/ов] осталось", мы говорим "Осталось %d элемент[а/ов]", соответственно фразу нельзя перевести "по кускам", только целиком.

**Comment by ctizen** [comment]
Кстати, если вы говорите про языки с разным количеством плюральных форм (в английском как мы знаем она одна, в русском две, а в арабском например целых пять) - то этот вопрос в gettext давно уже решен из коробки. Можно почитать про свойство plural-forms в PO-файлах, если интересно. https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

**Comment by Nihisil** [comment]
Я себе представляю это примерно так:

msgid "home_page.title"
msgtxt "Hello"

msgid "home_page.title"
msgtxt "Привет"

Я использовал такой подход в проекте с 12 языками, брат жив.

Только нужно иметь четкие правила как называть айдишники.

**Comment by ctizen** [comment]
Ну вот с таким подходом во-первых плейсхолдеры никуда не деваются, а во-вторых ты возлагаешь на i18n ещё и функцию смыслового наполнения. Как понять, что аналогичный идентификатор не использовался где-то ещё, но в ином смысле? Кроме того если строка не переведена на какой-то из языков, то сейчас она отобразится хотя бы на английском, а в твоём варианте вылезет вот это нечто :) 

К слову, я тоже использовал такой подход в одном проекте, брат конечно жив, только подход нерасширяемый никак, благо проект был маленький и руками поддерживать переводы было не столь сложно. В большом проекте на тысячи строк перевода мы в 2гис использовали текущий подход, правда исходный язык был русским, но это мелочи. Также весь workflow с gettext заточен не на абстрактные идентификаторы, а на конкретные строки. Не хочется изобретать лишних велосипедов.

Можно посмотреть на более сложные варианты локализации типа xliff, но мне кажется что за большую гибкость придётся уплатить большим геморроем при поддержке.
