### ISSUE TITLE
Improve the display of average costs on user profile page

### ISSUE THREAD

**Issue by Nihisil** [MahjongPantheon/pantheon#344]
Displaying decimal parts for average costs is unnecessary and makes the stat look unnecessary complex. So, they may be removed.

And as an additional improvement, we can round the values up to the nearest hundred points. This is because an average deal of 1100 looks better than 1066 (this is a subjective point that can be discussed further). 

![image](https://github.com/MahjongPantheon/pantheon/assets/475367/884e49b9-eccf-4ddc-afca-2805edb9796b)

**Comment by HassanTanveer** [comment]
Hey, can you assign this issue to me?

Also, I think rounding up to the nearest hundredth is not necessary as then the change in average won't be reflected immediately. Let me know what you think.

**Comment by HassanTanveer** [comment]
Thanks. I've started working on this, will create the PR soon.
