### ISSUE TITLE
[Tyr] Display result points after payments in game log

### ISSUE THREAD

**Issue by ctizen** [MahjongPantheon/pantheon#347]
See screenshot. Round result scores should be displayed after payments (now initial round scores are displayed)

![telegram-cloud-photo-size-2-5418295076234316406-y](https://github.com/MahjongPantheon/pantheon/assets/3592728/77a635a9-f310-4905-ab2e-d32438cbda5d)

**Comment by Oziabr** [comment]
please just push this line to the top of the div:
https://github.com/MahjongPantheon/pantheon/blob/master/Tyr/app/components/screens/log/view/RoundResult.tsx#L42

it will give consistency to the stats
