### ISSUE TITLE
[Forseti] Chombo payment is not nullified when "Pay chombo as reverse mangan" is selected

### ISSUE THREAD

**Issue by ctizen** [MahjongPantheon/pantheon#348]
Steps to reproduce:
- Make new event
- Uncheck "Pay chombo as reverse mangan" and set chombo to -20000
- Save changes
- Check "Pay chombo as reverse mangan" box again
- Save changes
`rulesetConfig`->`chomboPayments` will still be -20000, which is incorrect.

**Comment by Nefariusmag** [comment]
The same problem, waiting

**Comment by ctizen** [comment]
Fixed in https://github.com/MahjongPantheon/pantheon/commit/7f258829fbc3a0c3d0417490384de942d4f2e85c
