### ISSUE TITLE
[Sigrun] Remove .00 from "Final game score" section

### ISSUE THREAD

**Issue by Nihisil** [MahjongPantheon/pantheon#365]
For the min/max/avg scores on a player's page, it doesn't make sense to display decimals because you can't win fractional points in a game.

![image](https://github.com/MahjongPantheon/pantheon/assets/67736692/d880d222-17c0-4897-a176-4199876452ba)

**Comment by Jesterboxboy** [comment]
There used to be a setting in the Rulesets to display scores as i.e. 26,1 instead of 26100, i couldn't find it now checking the code, so i am not sure if this has been removed. But if it is still possible, we should check, that this is still displayed correctly after removing decimals.

**Comment by Nihisil** [comment]
I believe what you mentioned is related to the rating deltas, not to the game scores

**Comment by Jesterboxboy** [comment]
@ctizen just confirmed that this option has been removed during refactoring, so you can ignore my comment.

**Comment by ctizen** [comment]
Fixed in https://github.com/MahjongPantheon/pantheon/commit/d12d6ccc17b1c48fe0ab0bf65136a89edc6bfd69
