### ISSUE TITLE
[Tyr] Sort players by the place on the final screen

### ISSUE THREAD

**Issue by Nihisil** [MahjongPantheon/pantheon#370]
Currently, players are sorted based on their winds, which doesn't make much sense for the final results screen.

As an example, the final screen from tenhou (where players are ranked by their place) would be a better format to follow:

<img width="676" alt="image" src="https://github.com/MahjongPantheon/pantheon/assets/475367/94afe070-adf4-4a5f-991a-73cf12aec0e3">

**Comment by ctizen** [comment]
@Nihisil I sorted players by score. It might come inconvenient in case of a bump, though, it covers almost all cases. I was a bit lazy to pass place through protocol.
