### ISSUE TITLE
[Forseti] Add "remove/anonymize" Button for User and Superuser

### ISSUE THREAD

**Issue by Jesterboxboy** [MahjongPantheon/pantheon#417]
In order to make it easier to adhere to the GDPR stipulation, that a user has to be able to ask for removal of his personal data, or do it him or herself, a "Remove Account" Button should be added to the user profile that replaces the username with a generic name, removes personal information such as email address and tenhou handle.

Ideally, that button should also be available to superadmins.

**Comment by ctizen** [comment]
Not closing this yet as superuser depersonalilze button is still TODO
