### ISSUE TITLE
При отсутствии фамилии, в мобильном интерфейсе отображается точка через пробел после имени

### ISSUE THREAD

**Issue by exchange12rocks** [MahjongPantheon/pantheon#42]
Код, ответственный за это:
https://github.com/MahjongPantheon/pantheon/blob/dacd54ed0dedaa1dbb13ce5f34d48cd6f71025c4/Rheda/src/controllers/RatingTable.php#L143-L147

Предлагаю, если в `$name` нет пробелов, возвращать просто `$name`, не пытаясь ничего с ним делать.

**Comment by ctizen** [comment]
Closed in favor of https://pantheon.myjetbrains.com/youtrack/issue/PNTN-231
