### ISSUE TITLE
Если за ханчан не собрано ни одной руки, отображается placeholder bestHandPlayers

### ISSUE THREAD

**Issue by exchange12rocks** [MahjongPantheon/pantheon#43]
https://gui.mjtop.net/eid70/game/d290b5ee8a0108d1ee03a6189bd22cf08aea7366

Предлагаю вместо этого писать "N/A"

**Comment by ctizen** [comment]
Closed in favor of https://pantheon.myjetbrains.com/youtrack/issue/PNTN-232
