### ISSUE TITLE
String extraction library can't find particular strings

### ISSUE THREAD

**Issue by ctizen** [MahjongPantheon/pantheon#609]
Example: https://github.com/MahjongPantheon/pantheon/blob/a4f59ccb6cc25e76e14a56ddc7fbfc37ce40fd4e/Sigrun/app/helpers/gameLog.ts#L64

Still there is no "all noten" string in https://github.com/MahjongPantheon/pantheon/blob/a4f59ccb6cc25e76e14a56ddc7fbfc37ce40fd4e/Sigrun/app/i18n/messages.pot

See https://github.com/ctizen/stex

**Comment by comographer** [comment]
![image](https://github.com/MahjongPantheon/pantheon/assets/79941327/2cf3318f-1539-405f-97e9-9afb26899e40)

The error messages for Predefined seating configuration in Forseti are also not included in the messages.pot

**Comment by comographer** [comment]
![스크린샷 2024-03-22 21 36 50](https://github.com/MahjongPantheon/pantheon/assets/79941327/170283e5-0a64-4232-91c7-1f618015c0c2)

"Open assistant" string is not included in the messages.pot for Forseti.
(The same string is included for Sigrun.)

**Comment by ctizen** [comment]
Thanks. First comment is not related to this ticket, so closing it now.
